name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Installing Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: nickel
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build WASM
        run: |
          (cd nickel; git fetch --unshallow) # Flakes needs non-shallow
          nix build nickel/#buildWasm
          ln -s result/nickel-repl nickel-repl
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci --only=production
      - run: npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          production-branch: 'master'
          production-deploy: ${{ github.event_name == 'push' }}
          publish-dir: 'public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
        if: github.repository == 'tweag/nickel-lang.org'
