name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2
      - name: Installing Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: nickel
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build WASM
        run: |
          git clone https://github.com/tweag/nickel
          nix build nickel/#buildWasm
          find -L result
